### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by odirjar** [anacrolix/multiless#4]
It looks like this has been pulled in by some open source projects, but since this project has no license, they are not authorized to use or distribute this code. Could you please consider adding a license to this project?

This discusses the challenges with not providing a license:
https://choosealicense.com/no-permission/

**Comment by anacrolix** [comment]
Fixed by https://github.com/anacrolix/multiless/commit/f3d27407d8f17a9bdb029898a3b48539bb1fa56a. Cheers
